name: Test Desktop
on:
  push:
    branches: [ "desktop_support" ]




concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true



jobs:
  test:
    strategy:
      matrix:
        config: [
          { target: macos, os: macos-latest, tasks: jvmTest},
          { target: linux, os: ubuntu-latest, tasks: jvmTest},
          { target: windows, os: windows-latest, tasks: jvmTest},
        ]
    runs-on: ${{ matrix.config.os }}
    name: Testing on ${{ matrix.config.target }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Test ${{ matrix.config.target }} targets
        continue-on-error: false
        run: ./gradlew ${{ matrix.config.tasks }}
